# Generated by Django 6.0.2 on 2026-02-26 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={},
        ),
        migrations.AddField(
            model_name='contributor',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='project_contributor', through='softdesk.Contributor', to=settings.AUTH_USER_MODEL, verbose_name='Contributeurs'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='softdesk.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Autheur'),
        ),
    ]
