# Generated by Django 6.0.2 on 2026-02-27 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0002_alter_issue_contributor_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='contributor_assigned',
            field=models.ForeignKey(limit_choices_to={'contributor__proj': models.F('projec')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_assigned', to=settings.AUTH_USER_MODEL, verbose_name='assigner au contributeur'),
        ),
    ]
