# Generated by Django 6.0.2 on 2026-03-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0004_alter_issue_contributor_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.SmallIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
