# Generated by Django 6.0.2 on 2026-03-05 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0005_user_age_user_can_be_contacted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
