# Generated by Django 6.0.2 on 2026-03-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
